@extends('pdf.reports_layout')



@section('content_pdf')
    <h1>BookLibrary</h1>
    <hr>
    <h2>My Leases Report</h2>
    <p>Generated by: {{$user}}</p>
    <p>Generated at: {{$timestamp}}</p>

    <table class="table table-sm" id="">
        <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Author</th>
            <th>Leased From</th>
            <th>Date</th>

        </tr>
        </thead>
        <tbody>
        @foreach($my_leases as $lease)
            <tr>
                <td>{{ $lease->id }}</td>
                <td>{{$lease->getBookDetailsByID($lease->book_id)[0]}}</td>
                <td>{{$lease->getBookDetailsByID($lease->book_id)[1]}}</td>
                <td>{{$lease->getUserByID($lease->leased_from_id)}}</td>
                <td>{{$lease->created_at}}</td>

            </tr>
        @endforeach
        </tbody>
    </table>
